plugins {
    id 'java'
}

group = 'org.terra.incognita'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.+'
    testImplementation 'ch.qos.logback:logback-classic:1.5.+', { transitive = true}
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.0.+'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.0.+'
}

test {
    useJUnitPlatform()
}