rootProject.name = 'ticket-digital'

include 'ticket-digital-parser'
project(':ticket-digital-parser').projectDir = file('projects/ticket-digital-parser')

include 'ticket-digital-data'
project(':ticket-digital-data').projectDir = file('projects/ticket-digital-data')

include 'ticket-digital-tickets-downloader'
project(':ticket-digital-tickets-downloader').projectDir = file('projects/ticket-digital-tickets-downloader')

include 'ticket-digital-launcher'
project(':ticket-digital-launcher').projectDir = file('projects/ticket-digital-launcher')

